### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by TheFlashBold** [dedmen/interceptTest#1]
Tried from reddit https://www.reddit.com/r/arma/comments/6dy7vg/lua_scripting_in_arma/
but how do i use?

**Comment by dedmen** [comment]
You compile the Intercept plugin. Load it together with Intercept and then.. use exactly like seen in the screenshot.

**Comment by TheFlashBold** [comment]
I already did but when running compileLua it gives me an error

**Comment by dedmen** [comment]
What error?...

**Comment by TheFlashBold** [comment]
Forgot to load intercept ...

**Comment by dedmen** [comment]
Thank you sir. You just made me laugh.

**Comment by TheFlashBold** [comment]
I was very destracted, when i was trying your code ...

**Comment by TheFlashBold** [comment]
Hast du vielleicht Lust mir zu helfen, das ganze für v8 Javascript zu machen?

**Comment by dedmen** [comment]
nein
